### Получить всех сотрудников
GET http://localhost:8080/employees
### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Test",
  "lastname": "Test",
  "departament": 1,
  "salary": 1000
}
### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Test2",
  "lastname": "Test2",
  "departament": 2,
  "salary": 3000
}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Test3",
  "lastname": "Test3",
  "departament": 2,
  "salary": 1000
}
### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Test4",
  "lastname": "Test4",
  "departament": 21,
  "salary": 2000
}
### Получить сумму зарплат по сотрудникам
GET http://localhost:8080/employees/salary/sum
### Получить сотрудников с минимальной зарплатой
GET http://localhost:8080//employees/salary/min
### Получить сотрудников с максимальной зарплатой
GET http://localhost:8080//employees/salary/max
### Получить сотрудников с зарплатой больше чем средняя
GET http://localhost:8080//employees/salary/moreThanAvarage
